problemId: 223
name: Alternative Reality
category: Moderate
summary: Count all alternative ways.
url: "https://www.codeeval.com/browse/223/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/moderate/223-alternative-reality/"
