problemId: 225
name: Testing
category: Easy
summary: Wanna try to be a tester?
url: "https://www.codeeval.com/browse/225/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/easy/225-testing/"
