problemId: 54
name: Cash Register
category: Moderate
summary: Determine the amount of change to be returned.
url: https://www.codeeval.com/browse/54/
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/moderate/054-cash-register/"
