problemId: 84
name: Balanced Smileys
category: Moderate
summary: Facebook Hacker Cup 2013 problem.
url: "https://www.codeeval.com/browse/84/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/moderate/084-balanced-smileys/"
