problemId: 39
name: Happy Numbers
category: Easy
summary: Determine if a number is a happy number or not.
url: "https://www.codeeval.com/browse/39/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/easy/039-happy-numbers/"
