problemId: 154
name: IP Package
category: Hard
summary: Calculate IP checksum.
url: "https://www.codeeval.com/browse/154/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/hard/154-ip-package/"
