problemId: 78
name: Sudoku
category: Moderate
summary: Determine if a grid layout is a valid sudoku solution.
url: "https://www.codeeval.com/browse/78/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/moderate/078-sudoku/"
