problemId: 110
name: Text to Number
category: Hard
summary: Convert English text representation of a number to a decimal number.
url: https://www.codeeval.com/browse/110/
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/hard/110-text-to-number/"
