problemId: 10
name: Mth to Last Element
category: Moderate
summary: Determine the Mth to last element of a list.
url: "https://www.codeeval.com/browse/10/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/moderate/010-mth-to-last-element/"
