problemId: 51
name: Closest Pair
category: Hard
summary: "Given a set of points in a two dimensional space, you will have to find the distance between the closest two points."
url: "https://www.codeeval.com/browse/51/"
