problemId: 126
name: Play With DNA
category: Hard
summary: Write an algorithm that a finds DNA segment in a given DNA string.
url: "https://www.codeeval.com/browse/126/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/hard/126-play-with-dna/"
