problemId: 209
name: Black or White
category: Moderate
summary: Find the smallest submatrix.
url: "https://www.codeeval.com/browse/209/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/moderate/209-black-or-white/"
