problemId: 137
name: Seek for an Intruder
category: Moderate
summary: Find the IP address of an intruder.
url: "https://www.codeeval.com/browse/137/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/moderate/137-seek-for-an-intruder/"
