problemId: 134
name: A Bus Network
category: Hard
summary: Try to save more time.
url: "https://www.codeeval.com/browse/134/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/hard/134-a-bus-network/"
