problemId: 159
name: Where Is Wi-Fi
category: Hard
summary: Find out in which buildings there are hotspots.
url: "https://www.codeeval.com/browse/159/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/hard/159-where-is-wi-fi/"
