problemId: 237
name: Panacea - Truth or Lie
category: Easy
summary: Check whether the virus was stopped by antivirus.
url: "https://www.codeeval.com/browse/237/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/easy/237-panacea-truth-or-lie/"
