problemId: 24
name: Sum of Integers From File
category: Easy
summary: Print the sum of integers read from a file.
url: https://www.codeeval.com/browse/24/
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/easy/024-sum-of-integers-from-file/"
