problemId: 28
name: String Searching
category: Hard
summary: Determine if substring match exists.
url: "https://www.codeeval.com/browse/28/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/hard/028-string-searching/"
