problemId: 224
name: Prisoner or Citizen
category: Hard
summary: In jail or at large?
url: "https://www.codeeval.com/browse/224/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/hard/224-prisoner-or-citizen/"
