problemId: 139
name: Working Experience
category: Easy
summary: Retrieve an actual value.
url: "https://www.codeeval.com/browse/139/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/easy/139-working-experience/"
