problemId: 33
name: Double Squares
category: Moderate
summary: "FaceBook Hacker Cup 2011: Output the number of ways to write X as the sum of two squares."
url: "https://www.codeeval.com/browse/33/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/moderate/033-double-squares/"
