problemId: 64
name: Climbing Stairs
category: Hard
summary: Count the number of ways to climb to the top of a staircase.
url: "https://www.codeeval.com/browse/64/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/hard/064-climbing-stairs/"
