problemId: 184
name: Burrows-Wheeler Transform
category: Moderate
summary: Complete file decompression by inverting BWT.
url: "https://www.codeeval.com/browse/184/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/moderate/184-burrows-wheeler-transform/"
