problemId: 104
name: Word to Digit
category: Easy
summary: Substitute words to digits.
url: https://www.codeeval.com/browse/104/
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/easy/104-word-to-digit/"
