problemId: 200
name: Sort Matrix Columns
category: Moderate
summary: Sort matrix columns from lowest to highest numbers.
url: "https://www.codeeval.com/browse/200/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/moderate/200-sort-matrix-columns/"
