problemId: 129
name: Routing Problem
category: Hard
summary: Find all the shortest paths for the package between two specified hosts.
url: "https://www.codeeval.com/browse/129/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/hard/129-routing-problem/"
