problemId: 122
name: Hidden Digits
category: Easy
summary: Try to look behind the scenes.
url: "https://www.codeeval.com/browse/122/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/easy/122-hidden-digits/"
