problemId: 153
name: Locks
category: Moderate
summary: Calculate unlocked doors.
url: "https://www.codeeval.com/browse/153/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/moderate/153-locks/"
