problemId: 44
name: Following Integer
category: Hard
summary: Determine the next number in a sequence.
url: "https://www.codeeval.com/browse/44/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/hard/044-following-integer/"
