problemId: 190
name: Number Operations
category: Moderate
summary: Determine if it is possible to produce the number 42 with five cards.
url: "https://www.codeeval.com/browse/190/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/moderate/190-number-operations/"
