problemId: 106
name: Roman Numerals
category: Easy
summary: Convert a cardinal number to a Roman numeral.
url: "https://www.codeeval.com/browse/106/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/easy/106-roman-numerals/"
