problemId: 214
name: Time to Eat
category: Easy
summary: Sort timestamps in the right order.
url: "https://www.codeeval.com/browse/214/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/easy/214-time-to-eat/"
