problemId: 32
name: Trailing String
category: Moderate
summary: Determine if a string 'B' occurs at the end of string 'A'.
url: https://www.codeeval.com/browse/32/
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/moderate/032-trailing-string/"
