problemId: 196
name: Swap Numbers
category: Easy
summary: Swap numbers surrounding a word.
url: "https://www.codeeval.com/browse/196/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/easy/196-swap-numbers/"
