problemId: 27
name: Decimal to Binary
category: Moderate
summary: Print the binary representation of a decimal number.
url: https://www.codeeval.com/browse/27/
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/moderate/027-decimal-to-binary/"
