problemId: 221
name: Organizational Hierarchy
category: Moderate
summary: Recreate the hierarchy tree.
url: "https://www.codeeval.com/browse/221/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/moderate/221-organizational-hierarchy/"
