problemId: 130
name: Sequence Transformation
category: Moderate
summary: Transform a binary sequence into a string.
url: "https://www.codeeval.com/browse/130/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/moderate/130-sequence-transformation/"
