problemId: 55
name: Type Ahead
category: Hard
summary: Building a type ahead feature.
url: "https://www.codeeval.com/browse/55/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/hard/055-type-ahead/"
