problemId: 77
name: Da Vyncy
category: Hard
summary: Recreate a document from a set of fragments.
url: "https://www.codeeval.com/browse/77/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/hard/077-da-vyncy/"
