problemId: 60
name: Grid Walk
category: Hard
summary: The number of grid points that can be accessed.
url: "https://www.codeeval.com/browse/60/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/hard/060-grid-walk/"
