problemId: 232
name: Not So Clever
category: Easy
summary: Simplicity is not always good.
url: "https://www.codeeval.com/browse/232/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/easy/232-not-so-clever/"
