problemId: 118
name: Seat Your Team Members
category: Hard
summary: Place the employees in a new office.
url: "https://www.codeeval.com/browse/118/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/hard/118-seat-your-team-members/"
