problemId: 12
name: First Non-Repeated Character
category: Moderate
summary: Find the first non repeated character in a string.
url: "https://www.codeeval.com/browse/12/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/moderate/012-first-non-repeated-character/"
