problemId: 176
name: Ray of Light
category: Hard
summary: Trace the path of light distribution.
url: "https://www.codeeval.com/browse/176/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/hard/176-ray-of-light/"
