problemId: 140
name: Data Recovery
category: Easy
summary: Reconstruct a sentence using hints.
url: "https://www.codeeval.com/browse/140/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/easy/140-data-recovery/"
