problemId: 83
name: Beautiful Strings
category: Easy
summary: Facebook Hacker Cup 2013 problem.
url: "https://www.codeeval.com/browse/83/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/easy/083-beautiful-strings/"
