problemId: 158
name: Interrupted Bubble Sort
category: Moderate
summary: Sort a list of elements. Partially.
url: "https://www.codeeval.com/browse/158/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/moderate/158-interrupted-bubble-sort/"
