problemId: 101
name: Find a Square
category: Moderate
summary: Do 4 points make a square?
url: "https://www.codeeval.com/browse/101/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/moderate/101-find-a-square/"
