problemId: 114
name: Package Problem
category: Hard
summary: Put as many things into a package as possible.
url: "https://www.codeeval.com/browse/114/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/hard/114-package-problem/"
