problemId: 170
name: Guess the Number
category: Moderate
summary: Guess the number in log2(N) steps.
url: "https://www.codeeval.com/browse/170/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/moderate/170-guess-the-number/"
