problemId: 23
name: Multiplication Tables
category: Easy
summary: "Print out the grade school multiplication table upto 12*12."
url: "https://www.codeeval.com/browse/23/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/easy/023-multiplication-tables/"
