problemId: 171
name: DNA Alignment
category: Hard
summary: Find the highest score of DNA sequences alignment.
url: "https://www.codeeval.com/browse/171/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/hard/171-dna-alignment/"
