problemId: 202
name: Stepwise Word
category: Easy
summary: Print the longest word in a stepwise manner.
url: "https://www.codeeval.com/browse/202/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/easy/202-stepwise-word/"
