problemId: 105
name: Largest Sub-Matrix
category: Hard
summary: Determine the largest sub-matrix in a matrix.
url: "https://www.codeeval.com/browse/105/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/hard/105-largest-sub-matrix/"
