problemId: 142
name: Visit to the Headquarters
category: Hard
summary: Organize the queues.
url: "https://www.codeeval.com/browse/142/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/hard/142-visit-to-the-headquarters/"
