problemId: 56
name: Robot Movements
category: Hard
summary: Number of ways a robot can reach its destination.
url: "https://www.codeeval.com/browse/56/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/hard/056-robot-movements/"
