problemId: 13
name: Remove Characters
category: Moderate
summary: Delete specific characters from a string.
url: https://www.codeeval.com/browse/13/
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/moderate/013-remove-characters/"
