problemId: 47
name: Palindromic Ranges
category: Hard
summary: Find out a range of palindromic numbers.
url: "https://www.codeeval.com/browse/47/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/hard/047-palindromic-ranges/"
