problemId: 53
name: Repeated Substring
category: Hard
summary: Find the longest repeated substring in a given text.
url: "https://www.codeeval.com/browse/53/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/hard/053-repeated-substring/"
