problemId: 107
name: Shortest Repetition
category: Easy
summary: Find the shortest repetition in a string.
url: "https://www.codeeval.com/browse/107/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/easy/107-shortest-repetition/"
