problemId: 8
name: Reverse Words
category: Easy
summary: Reversing an input sequence of words.
url: https://www.codeeval.com/browse/8/
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/easy/008-reverse-words/"
