problemId: 88
name: Juggle Fest
category: Hard
summary: A challenge from Yodle.
url: "https://www.codeeval.com/browse/88/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/hard/088-juggle-fest/"
