problemId: 156
name: Roller Coaster
category: Easy
summary: Turn the text into RoLlErCoAsTeR case.
url: "https://www.codeeval.com/browse/156/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/easy/156-roller-coaster/"
