problemId: 125
name: Predict the Number
category: Moderate
summary: Try to go beyond the limits.
url: "https://www.codeeval.com/browse/125/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/moderate/125-predict-the-number/"
