problemId: 38
name: String List
category: Hard
summary: Create a new string from constituent alphabets.
url: "https://www.codeeval.com/browse/38/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/hard/038-string-list/"
