problemId: 177
name: Justify the Text
category: Moderate
summary: Align the text to the specified width.
url: "https://www.codeeval.com/browse/177/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/moderate/177-justify-the-text/"
