problemId: 179
name: Broken LCD
category: Moderate
summary: Determine whether a given number can be displayed on the damaged LCD.
url: https://www.codeeval.com/browse/179/
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/moderate/179-broken-lcd/"
