problemId: 168
name: The Frequency
category: Hard
summary: Find the signals frequency.
url: "https://www.codeeval.com/browse/168/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/hard/168-the-frequency/"
