problemId: 143
name: The Ministry of Truth
category: Moderate
summary: Your task is to help the Big Brother.
url: "https://www.codeeval.com/browse/143/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/moderate/143-the-ministry-of-truth/"
