problemId: 192
name: Compare Points
category: Easy
summary: "Given two (x, y) points A and B, determine which cardinal direction B is from A."
url: "https://www.codeeval.com/browse/192/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/easy/192-compare-points/"
