problemId: 166
name: Delta Time
category: Easy
summary: Find the time difference.
url: "https://www.codeeval.com/browse/166/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/easy/166-delta-time/"
