problemId: 150
name: Roman and Arabic
category: Moderate
summary: Calculate aromatic numbers.
url: "https://www.codeeval.com/browse/150/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/moderate/150-roman-and-arabic/"
