problemId: 212
name: Robo and Robitta
category: Moderate
summary: Count all nuts.
url: "https://www.codeeval.com/browse/212/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/moderate/212-robo-and-robitta/"
