problemId: 68
name: Valid Parentheses
category: Moderate
summary: Determine if string is a well-formed parentheses.
url: "https://www.codeeval.com/browse/68/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/moderate/068-valid-parentheses/"
