problemId: 76
name: String Rotation
category: Moderate
summary: Find if a string is the rotation of another string.
url: https://www.codeeval.com/browse/76/
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/moderate/076-string-rotation/"
