problemId: 123
name: Efficient Delivery
category: Hard
summary: Load your tankers with oil.
url: "https://www.codeeval.com/browse/123/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/hard/123-efficient-delivery/"
