problemId: 89
name: Pass Triangle
category: Moderate
summary: Lead the way within the triangle.
url: "https://www.codeeval.com/browse/89/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/moderate/089-pass-triangle/"
