problemId: 195
name: Crime House
category: Hard
summary: Count criminals in the Crime House.
url: "https://www.codeeval.com/browse/195/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/hard/195-crime-house/"
