problemId: 133
name: City Blocks Flyover
category: Moderate
summary: Chart the path of a helicopter from above to discover how many city blocks it flew over.
url: "https://www.codeeval.com/browse/133/"
