problemId: 109
name: Bay Bridges
category: Hard
summary: Build Bridges Over San Francisco Bay.
url: "https://www.codeeval.com/browse/109/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/hard/109-bay-bridges/"
