problemId: 117
name: A Pile of Bricks
category: Moderate
summary: Close a hole in a wall.
url: "https://www.codeeval.com/browse/117/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/moderate/117-a-pile-of-bricks/"
