problemId: 145
name: Running for President
category: Hard
summary: Build your strategy to win the Presidency of the United States.
url: "https://www.codeeval.com/browse/145/"
mirror: "https://github.com/rdtsc/codeeval-problem-statements/tree/master/hard/145-running-for-president/"
